# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Create Migration

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      name:
        type: string
        description: "name of your migrations; eg: create-table-users"
        required: true
      directory:
        type: string
        description: "directory where you store the migration files"
        required: true


jobs:

  build:
    name: create migration
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Install golang-migrate
      run: go install -tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate@latest

    - name: Create new branch
      run: git checkout -b ${{ github.event.inputs.name }}

    - name: Create migration file
      run: migrate create -ext sql -dir migrations -seq ${{ github.event.inputs.name }}

    - name: Push branch
      run: git push origin ${{ github.event.inputs.name }}

