name: Deployment

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Which environment you would like to deploy this service to
        options:
          - DEV
          - PROD

jobs:

  build:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Install golang-migrate
        run: go install -tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate@latest

      - name: Run Unit Test
        run: go test -race -cover -v ./...

      - name: Run Migrations
        run: migrate -database ${{ secrets.POSTGRESQL_URL }} -path migrations ${{ github.event.inputs.migrate }} up

  generateEnv:
    runs-on: ubuntu-latest
    steps:
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_PORT: ${{ secrets.SERVICE_PORTS }}
          envkey_DB_HOST: ${{ secrets.DB_HOST }}
          envkey_DB_PORT: ${{ secrets.DB_PORT }}
          envkey_DB_USER: ${{ secrets.DB_USER }}
          envkey_DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          envkey_DB_NAME: btc_billionaire
          # directory: common
          file_name: app.env
          fail_on_empty: false

  deploy:
    runs-on: ubuntu-latest
    needs: [build, generateEnv]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Cloud cli
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${{ secrets.GCP_PROJECT }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Authorize Docker push
        run: gcloud auth configure-docker

      - name: Build and Push Container
        run: |-
          docker build -t gcr.io/${{ secrets.GCP_PROJECT }}/btc-billionaire:${{  github.sha }} .
          docker push gcr.io/${{ secrets.GCP_PROJECT }}/btc-billionaire:${{  github.sha }}
      - name: Deploy to Cloud Run
        id: gohibeesh
        uses: google-github-actions/deploy-cloudrun@v0.4.0
        with:
          service: btc-billionaire
          image: gcr.io/${{ secrets.GCP_PROJECT }}/btc-billionaire:${{  github.sha }}
          region: us-west1

      - name: Show Output
        run: echo ${{ steps.gohibeesh.outputs.url }}
