name: Semantic Release

permissions:
  contents: write

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Semantic Release
      uses: codfish/semantic-release-action@v2
      with:
        repository_url: https://github.com/mhdiiilham/BTC-Billionaire.git
        tag_format: 'v${version}'
        # You can specify specifying version range for the extra plugins if you prefer.
        additional_packages: |
          ['@semantic-release/git', '@semantic-release/changelog']
        plugins: |
          ['@semantic-release/commit-analyzer', '@semantic-release/release-notes-generator', '@semantic-release/github' '@semantic-release/git']
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    
