name: Bump Version
on:
  push:
    branches:
      - main

jobs:
  # build:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: go-semantic-release/action@v1
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          changelog-file: 'CHANGELOG.md'
          changelog-generator-opt: "emojis=true"
    # runs-on: ubuntu-latest
    # steps:
    # - uses: actions/checkout@master
    # - name: Bump version and push tag
    #   uses: anothrNick/github-tag-action@master
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    #     REPO_OWNER: mhdiiilham
    #     WITH_V: true
